### ISSUE TITLE
Explain new permissions

### ISSUE THREAD

**Issue by valrus** [BlaseballCrabs/blaseball-plus#1]
Hello and thanks for Blaseball+! The new version requires the following new permission:
```
Access your data for d35iw2jmbg6ut8.cloudfront.net
```

I think this is probably not malicious but it sure looks sketchy. Can you explain what it is, ideally in the public-facing description on the [addons page](https://addons.mozilla.org/en-US/firefox/addon/blaseball-plus)?

**Comment by leo60228** [comment]
That's the CDN for Blaseball's CSS and JS. I'm not sure where the best place to explain this is, since the description isn't prominently referenced in the permission prompt.

**Comment by valrus** [comment]
Thanks! I'm not sure either, but for me personally, the addons page was the first place I looked. (This was the second, so maybe other interested parties can find this discussion without your having to do anything.)

**Comment by leo60228** [comment]
I've added clarification to the description on addons.mozilla.org. I'll ask on the Mozilla Matrix if there's a better place to put this info.

**Comment by leo60228** [comment]
Don't think there's a better option here, closing.
